import { z } from "zod";
import { safeFetch } from "../../security/url.js";
import type { ToolModule } from "../types.js";

const maxBodyBytes = 1024 * 1024;
const textPreviewChars = 120000;

const publicApiInputSchema = z.object({
  timeoutMs: z.number().int().min(1000).max(30000).optional().default(10000),
  responseMode: z.enum(["parsed", "raw"]).optional().default("parsed")
}).strict();

type PublicApiSpec = {
  id: string;
  name: string;
  category: string;
  endpoint: string;
  responseType: "json" | "xml" | "image";
  description: string;
  usage: { status: string; licence: string; commercial: string; notes: string };
  requestHeaders?: Record<string, string>;
};

// API Workbench SSOT v3 no-key APIs that can be called as fixed GET endpoints.
// POST-only no-key APIs are intentionally excluded from this v1 tool set.
export const publicApiRegistry = [
  { id: "arxiv-search", name: "arXiv Search", category: "Academic", endpoint: "https://export.arxiv.org/api/query?search_query=all:retrieval%20augmented%20generation&start=0&max_results=8", responseType: "xml", description: "arXiv Atom/XML paper search feed.", usage: {"status":"caution","licence":"arXiv API terms; article licences vary by paper.","commercial":"Good for paper discovery demos. Full paper reuse depends on each paper licence.","notes":"Respect request delays and cache."} },
  { id: "crossref-works", name: "Crossref Works", category: "Academic", endpoint: "https://api.crossref.org/works?query=machine%20learning&rows=8", responseType: "json", description: "Scholarly publication metadata search.", usage: {"status":"caution","licence":"Crossref metadata/API terms; use polite pool where possible.","commercial":"Public access is allowed, but production should identify itself and respect rate limits.","notes":"Use mailto/User-Agent and cache."} },
  { id: "gbif-species", name: "GBIF Species Search", category: "Bio", endpoint: "https://api.gbif.org/v1/species/search?q=orchid&limit=8", responseType: "json", description: "Biodiversity species and taxonomy search.", usage: {"status":"caution","licence":"GBIF-mediated dataset-specific licences, including possible CC BY-NC records.","commercial":"Commercial use depends on each dataset licence; attribution required.","notes":"Show dataset/source attribution."} },
  { id: "gutendex", name: "Gutendex Books", category: "Books", endpoint: "https://gutendex.com/books/?search=singapore", responseType: "json", description: "Project Gutenberg book metadata.", requestHeaders: {"User-Agent": "Mozilla/5.0 (compatible; DemoBot/1.0)"}, usage: {"status":"caution","licence":"Gutendex / Project Gutenberg terms.","commercial":"Good for demos. Verify text/trademark/country restrictions before republishing.","notes":"Do not assume every linked text can be republished everywhere."} },
  { id: "open-library-covers", name: "Open Library Covers API", category: "Books", endpoint: "https://covers.openlibrary.org/b/isbn/9780140328721-M.jpg", responseType: "image", description: "Book cover image API for book card/gallery demos.", usage: {"status":"caution","licence":"Open Library / Internet Archive terms; cover image rights can vary.","commercial":"Good for UI demos. Verify cover image rights before commercial publication.","notes":"Use as linked cover image and show source."} },
  { id: "open-library", name: "Open Library Search", category: "Books", endpoint: "https://openlibrary.org/search.json?q=singapore&limit=8", responseType: "json", description: "Book search and metadata API.", usage: {"status":"caution","licence":"Open Library / Internet Archive terms and record-specific licences.","commercial":"Good for discovery demos; avoid heavy commercial backend usage without permission/cache.","notes":"Respect public-good purpose."} },
  { id: "dummy-products", name: "DummyJSON Products", category: "Business", endpoint: "https://dummyjson.com/products?limit=8", responseType: "json", description: "Product catalogue data for ERP inventory, product admin, cards, table, and detail demos.", usage: {"status":"demo-only","licence":"Provider/project terms; mock data.","commercial":"Good for prototypes, training, UI demos, and internal screenshots. Replace before production.","notes":"Do not treat fake product data as production business data."} },
  { id: "dummy-users", name: "DummyJSON Users", category: "Business", endpoint: "https://dummyjson.com/users?limit=8&select=firstName,lastName,email,phone,company,role,image", responseType: "json", description: "User master data for CRM, staff directory, admin table, and mobile contact cards.", usage: {"status":"demo-only","licence":"Provider/project terms; mock/generated data.","commercial":"Good for CRM/staff UI prototypes. Replace with real backend before production.","notes":"Generated users are not real customer or HR data."} },
  { id: "json-posts", name: "JSONPlaceholder Posts", category: "Business", endpoint: "https://jsonplaceholder.typicode.com/posts?_limit=8", responseType: "json", description: "Simple post/comment REST data for fetch, list rendering, and CRUD flow.", usage: {"status":"demo-only","licence":"Provider/project terms; mock data.","commercial":"Good for fetch/CRUD learning. Not a production data source.","notes":"Fake posts/comments only."} },
  { id: "open-brewery", name: "Open Brewery DB", category: "Business", endpoint: "https://api.openbrewerydb.org/v1/breweries?per_page=8&by_country=united_states", responseType: "json", description: "Brewery location records for directory, listing, map, and vendor-style demos.", usage: {"status":"caution","licence":"Provider/open data terms.","commercial":"Suitable for demos and light directory prototypes. Verify current terms before commercial use.","notes":"Use cache for repeated calls."} },
  { id: "random-user", name: "RandomUser Contacts", category: "Business", endpoint: "https://randomuser.me/api/?results=8", responseType: "json", description: "Generated contact profiles with names, email, phone, location, and avatars.", usage: {"status":"demo-only","licence":"Provider/project terms; generated identities.","commercial":"Good for contact/profile UI prototypes. Do not present as real users.","notes":"Generated identity data only."} },
  { id: "nager", name: "Nager.Date Holidays", category: "Calendar", endpoint: "https://date.nager.at/api/v3/PublicHolidays/2026/SG", responseType: "json", description: "Public holiday data for leave planner and HR demos.", usage: {"status":"business-ok","licence":"Provider/open-source terms.","commercial":"Generally suitable for prototypes and light production; verify current terms.","notes":"Holiday rules can change; refresh before HR/payroll deadlines."} },
  { id: "uk-bank-holidays", name: "UK Bank Holidays", category: "Calendar", endpoint: "https://www.gov.uk/bank-holidays.json", responseType: "json", description: "UK government bank holiday JSON feed.", usage: {"status":"business-ok","licence":"UK Open Government Licence / GOV.UK terms.","commercial":"Suitable for demo and commercial use subject to attribution rules.","notes":"Show source in polished apps."} },
  { id: "devto", name: "DEV.to / Forem API", category: "Developer", endpoint: "https://dev.to/api/articles?per_page=8&tag=javascript", responseType: "json", description: "Developer articles feed for tech news, digest, and content dashboard demos.", usage: {"status":"caution","licence":"Forem/DEV API terms; V1 uses accept header and many endpoints require API key.","commercial":"Good for developer feed demos. Respect content rights and API version guidance.","notes":"Do not treat article content as your own."} },
  { id: "github", name: "GitHub Public Repos", category: "Developer", endpoint: "https://api.github.com/users/octocat/repos?per_page=8", responseType: "json", description: "Public GitHub repository metadata.", usage: {"status":"caution","licence":"GitHub API terms plus repository-specific licences.","commercial":"Public metadata OK; repo code/content rights depend on each repository licence.","notes":"Unauthenticated rate limit is low."} },
  { id: "hacker-news", name: "Hacker News API", category: "Developer", endpoint: "https://hacker-news.firebaseio.com/v0/item/8863.json?print=pretty", responseType: "json", description: "Public Hacker News story/comment/job data.", usage: {"status":"caution","licence":"Official HN API docs/code terms are not the same as user content rights.","commercial":"Good for demos and internal tools. Do not treat HN content as MIT.","notes":"Respect source links and content rights."} },
  { id: "ipify-public-ip", name: "ipify Public IP", category: "Developer", endpoint: "https://api64.ipify.org?format=json", responseType: "json", description: "Simple public IPv4/IPv6 address lookup for network, firewall, login audit, and diagnostics demos.", usage: {"status":"business-ok","licence":"ipify public API; open-source project.","commercial":"Good for diagnostics demos and internal tools. For IP geolocation, use a separate licensed service.","notes":"Returns only the caller public IP address; no geolocation or identity data."} },
  { id: "npm-search", name: "npm Registry Search", category: "Developer", endpoint: "https://registry.npmjs.org/-/v1/search?text=react&size=8", responseType: "json", description: "npm package search data.", usage: {"status":"caution","licence":"npm registry terms; package licences vary by package.","commercial":"Good for developer demos. Do not assume package code is commercially usable.","notes":"Check each package licence."} },
  { id: "nvd-cpe-search", name: "NVD CPE Search", category: "Developer", endpoint: "https://services.nvd.nist.gov/rest/json/cpes/2.0?keywordSearch=openssl&resultsPerPage=8", responseType: "json", description: "NVD CPE product search for matching software names to security inventory records.", usage: {"status":"business-ok","licence":"NIST/NVD public data terms; display the NVD source notice and do not imply endorsement.","commercial":"Usable in commercial and internal tools with attribution/no-endorsement notice and rate-limit handling.","notes":"No-key public limit is 5 requests in a rolling 30-second window. Cache results for real tools."} },
  { id: "nvd-cve-detail", name: "NVD CVE Detail", category: "Developer", endpoint: "https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-3094", responseType: "json", description: "Single CVE detail lookup for vulnerability detail pages and security investigation demos.", usage: {"status":"business-ok","licence":"NIST/NVD public data terms; display the NVD source notice and do not imply endorsement.","commercial":"Usable in commercial and internal tools with attribution/no-endorsement notice and rate-limit handling.","notes":"No-key public limit is 5 requests in a rolling 30-second window. Cache detail lookups."} },
  { id: "nvd-cves", name: "NVD CVE Search", category: "Developer", endpoint: "https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch=postgresql&resultsPerPage=8", responseType: "json", description: "NIST National Vulnerability Database CVE search for security and dependency-risk dashboards.", usage: {"status":"business-ok","licence":"NIST/NVD public data terms; display the NVD source notice and do not imply endorsement.","commercial":"Usable in commercial and internal tools with attribution/no-endorsement notice and strict rate-limit handling.","notes":"No-key public limit is low: 5 requests in a rolling 30-second window. Add delay/cache for real tools."} },
  { id: "nvd-recent-cves", name: "NVD Recently Modified CVEs", category: "Developer", endpoint: "https://services.nvd.nist.gov/rest/json/cves/2.0?lastModStartDate=2026-06-15T00:00:00.000&lastModEndDate=2026-06-22T00:00:00.000&resultsPerPage=8", responseType: "json", description: "NVD modified CVE sample for security dashboard and patch-monitoring demos.", usage: {"status":"business-ok","licence":"NIST/NVD public data terms; display the NVD source notice and do not imply endorsement.","commercial":"Usable in commercial and internal tools with attribution/no-endorsement notice and rate-limit handling.","notes":"No-key public limit is 5 requests in a rolling 30-second window. Update the date range for live monitoring."} },
  { id: "pypi-json", name: "PyPI JSON API", category: "Developer", endpoint: "https://pypi.org/pypi/requests/json", responseType: "json", description: "Python package metadata.", usage: {"status":"caution","licence":"PyPI API/docs terms; package licences vary by project.","commercial":"Good for developer demos. Check each package licence before using code/content commercially.","notes":"Package metadata != package code licence."} },
  { id: "stack-exchange", name: "Stack Exchange Questions", category: "Developer", endpoint: "https://api.stackexchange.com/2.3/questions?order=desc&sort=activity&tagged=javascript&site=stackoverflow&pagesize=8", responseType: "json", description: "Stack Overflow question feed.", usage: {"status":"caution","licence":"Stack Exchange API terms; user-generated content generally CC BY-SA.","commercial":"Reuse needs attribution/share-alike. Good for developer Q&A dashboards.","notes":"Show source links/attribution."} },
  { id: "data-usa", name: "Data USA API", category: "Economy", endpoint: "https://api.datausa.io/api/data?drilldowns=Nation&measures=Population", responseType: "json", description: "US demographic/economic data for population and economy dashboards.", usage: {"status":"business-ok","licence":"Data USA/public data terms and source attribution apply.","commercial":"Good for economic and demographic demos if source is shown.","notes":"Check data provenance before commercial redistribution."} },
  { id: "world-bank-gdp", name: "World Bank GDP", category: "Economy", endpoint: "https://api.worldbank.org/v2/country/SGP/indicator/NY.GDP.MKTP.CD?format=json&per_page=8", responseType: "json", description: "World Bank GDP indicator data for economic dashboards.", usage: {"status":"business-ok","licence":"World Bank API/data terms; attribution recommended.","commercial":"Often suitable for economic dashboards when source and indicator are shown.","notes":"Show source and indicator name."} },
  { id: "world-bank-population", name: "World Bank Population", category: "Economy", endpoint: "https://api.worldbank.org/v2/country/SGP/indicator/SP.POP.TOTL?format=json&per_page=8", responseType: "json", description: "World Bank country population time series.", usage: {"status":"business-ok","licence":"World Bank API/data terms; attribution recommended.","commercial":"Often suitable for business dashboards when source and indicator are shown.","notes":"Check indicator metadata and update frequency."} },
  { id: "carbon-intensity-gb", name: "Carbon Intensity GB", category: "Environment", endpoint: "https://api.carbonintensity.org.uk/intensity", responseType: "json", description: "Great Britain carbon intensity forecast for ESG, energy and sustainability dashboard demos.", usage: {"status":"business-ok","licence":"Carbon Intensity API data is licensed under CC BY 4.0; attribution required.","commercial":"Good for ESG and energy demos when attribution is shown and terms are followed.","notes":"No authentication required for this endpoint. Show source and methodology in polished dashboards."} },
  { id: "fiscal-data-treasury", name: "Fiscal Data Treasury API", category: "Finance", endpoint: "https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_to_penny?page[size]=8", responseType: "json", description: "US Treasury fiscal data API for debt and finance dashboards.", usage: {"status":"business-ok","licence":"US Treasury/Fiscal Data public API terms and dataset notices.","commercial":"Good for public finance dashboards with source attribution and no-warranty awareness.","notes":"Check dataset metadata and update frequency."} },
  { id: "frankfurter", name: "Frankfurter Forex", category: "Finance", endpoint: "https://api.frankfurter.dev/v1/latest?from=SGD&to=MYR,USD,EUR", responseType: "json", description: "Exchange rate API for ERP invoice, forex helper, and currency converter demos.", usage: {"status":"caution","licence":"Open-source/provider terms; underlying forex data terms may apply.","commercial":"Useful for demos. Verify accuracy/licence before accounting, trading, or invoice usage.","notes":"Not financial advice."} },
  { id: "sec-company-facts", name: "SEC Company Facts", category: "Finance", endpoint: "https://data.sec.gov/api/xbrl/companyfacts/CIK0000320193.json", responseType: "json", description: "US SEC public company XBRL facts for finance/company dashboard demos.", requestHeaders: {"User-Agent": "APIAtlasDemo admin@example.com"}, usage: {"status":"caution","licence":"SEC public data terms and fair-access rules.","commercial":"Can support company dashboards. Use proper User-Agent and avoid high-frequency scraping.","notes":"Not legal, investment, or accounting advice."} },
  { id: "open-trivia", name: "Open Trivia DB", category: "Fun", endpoint: "https://opentdb.com/api.php?amount=6&type=multiple&encode=url3986", responseType: "json", description: "Trivia question API for quiz demos.", usage: {"status":"caution","licence":"Open Trivia DB terms; question content may have source considerations.","commercial":"Good for quiz demos. Verify terms before commercial game usage.","notes":"Respect rate limits."} },
  { id: "pokeapi", name: "PokéAPI List", category: "Fun", endpoint: "https://pokeapi.co/api/v2/pokemon?limit=8", responseType: "json", description: "Pokémon list API for learning demos.", usage: {"status":"demo-only","licence":"PokéAPI project terms plus Pokémon IP rights.","commercial":"Learning/demo only. Pokémon names/assets are protected IP.","notes":"Avoid commercial branding."} },
  { id: "chess-profile", name: "Chess.com Player Profile", category: "Game", endpoint: "https://api.chess.com/pub/player/hikaru", responseType: "json", description: "Public Chess.com player profile data.", usage: {"status":"caution","licence":"Chess.com Published Data API terms.","commercial":"Good for game profile dashboards. Avoid bulk/parallel requests.","notes":"Public player data only."} },
  { id: "nominatim", name: "Nominatim Place Search", category: "Geo", endpoint: "https://nominatim.openstreetmap.org/search?q=Aperia%20Mall%20Singapore&format=json&limit=5", responseType: "json", description: "OpenStreetMap geocoding for place search.", usage: {"status":"caution","licence":"OSM data under ODbL; strict Nominatim public-service policy.","commercial":"Demo only unless deliberately compliant. Commercial geocoding-heavy products need own service/paid provider.","notes":"Limit requests, use attribution, no autocomplete/bulk use."} },
  { id: "opentopodata", name: "OpenTopoData Elevation", category: "Geo", endpoint: "https://api.opentopodata.org/v1/aster30m?locations=1.3521,103.8198", responseType: "json", description: "Elevation data API for terrain, maps, travel, and route context demos.", usage: {"status":"caution","licence":"OpenTopoData terms and dataset-specific source licences apply.","commercial":"Good for elevation demos. Verify dataset licence and rate limits before business use.","notes":"Not for safety-critical terrain/navigation."} },
  { id: "overpass-api", name: "Overpass API", category: "Geo", endpoint: "https://overpass-api.de/api/interpreter?data=%5Bout%3Ajson%5D%5Btimeout%3A25%5D%3Bnode%28around%3A600%2C1.3521%2C103.8198%29%5Bhighway%3Dbus_stop%5D%3Bout%20tags%2010%3B", responseType: "json", description: "Query OpenStreetMap POIs such as nearby bus stops, amenities, buildings, and route features.", usage: {"status":"caution","licence":"OpenStreetMap data is ODbL; Overpass API software is AGPL; public instance policy applies.","commercial":"Good for SGTransit and nearby POI demos. Commercial products should consider own Overpass instance or provider.","notes":"Public instance usage should stay polite, identifiable, and cached."} },
  { id: "postcodes-io", name: "Postcodes.io", category: "Geo", endpoint: "https://api.postcodes.io/postcodes/SW1A1AA", responseType: "json", description: "UK postcode lookup and geolocation data.", usage: {"status":"business-ok","licence":"Postcodes.io is MIT licensed; upstream postcode data rights still matter.","commercial":"Good for business demos and prototypes; verify upstream data licensing for production resale/redistribution.","notes":"Show source for polished demos."} },
  { id: "usgs", name: "USGS Earthquakes", category: "Geo", endpoint: "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson", responseType: "json", description: "Earthquake GeoJSON feed for map and alert dashboards.", usage: {"status":"business-ok","licence":"USGS / US public data terms; no warranty.","commercial":"Generally usable for demos and commercial dashboards with attribution/no warranty.","notes":"Not a replacement for emergency systems."} },
  { id: "socrata-open-data", name: "Socrata SODA API", category: "Government", endpoint: "https://data.cityofnewyork.us/resource/erm2-nwe9.json?$limit=8", responseType: "json", description: "Socrata open data API used by many city/government portals.", usage: {"status":"caution","licence":"Socrata dataset/API terms vary by portal; app token improves throttling.","commercial":"Good for government data demos. Verify dataset licence and use app token for production.","notes":"No-token calls can be throttled by IP."} },
  { id: "clinical-trials", name: "ClinicalTrials.gov", category: "Health", endpoint: "https://clinicaltrials.gov/api/v2/studies?query.term=diabetes&pageSize=8&format=json", responseType: "json", description: "Clinical study search data.", usage: {"status":"caution","licence":"ClinicalTrials.gov / US government data terms and disclaimers.","commercial":"Good for research dashboards. Not medical advice.","notes":"Show NCT ID/source."} },
  { id: "openfda-drug-events", name: "openFDA Drug Events", category: "Health", endpoint: "https://api.fda.gov/drug/event.json?search=receivedate:[20240101+TO+20241231]&limit=8", responseType: "json", description: "US FDA adverse event records.", usage: {"status":"caution","licence":"openFDA terms and no-key/API-key limits.","commercial":"Good for compliance demos. Not medical advice. Use API key for heavier use.","notes":"No-key limit is low."} },
  { id: "loc-search", name: "Library of Congress API", category: "Knowledge", endpoint: "https://www.loc.gov/search/?fo=json&q=singapore&c=8", responseType: "json", description: "Library of Congress collections search.", requestHeaders: {"User-Agent": "Mozilla/5.0 (compatible; DemoBot/1.0)"}, usage: {"status":"caution","licence":"Library of Congress API/data terms; item rights vary.","commercial":"Good for demo search/gallery. Verify rights for each item before commercial publication.","notes":"Show source and rights metadata."} },
  { id: "wikidata-sparql", name: "Wikidata SPARQL", category: "Knowledge", endpoint: "https://query.wikidata.org/sparql?query=SELECT%20%3Fitem%20%3FitemLabel%20WHERE%20%7B%20%3Fitem%20wdt%3AP31%20wd%3AQ515%20.%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%7D%20%7D%20LIMIT%208&format=json", responseType: "json", description: "Structured knowledge graph SPARQL endpoint.", usage: {"status":"business-ok","licence":"Wikidata data is CC0; endpoint fair-use applies.","commercial":"Data broadly reusable; keep SPARQL queries small and cached.","notes":"Avoid heavy endpoint load."} },
  { id: "wikipedia-search", name: "Wikipedia Search", category: "Knowledge", endpoint: "https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=Singapore&format=json&origin=*", responseType: "json", description: "Wikipedia article search.", usage: {"status":"caution","licence":"Wikipedia content licences, generally CC BY-SA/GFDL.","commercial":"Reusable with attribution/share-alike obligations. API access is not ownership of article text.","notes":"Show source/article links."} },
  { id: "datamuse", name: "Datamuse API", category: "Language", endpoint: "https://api.datamuse.com/words?ml=demo&max=8", responseType: "json", description: "Word suggestion and writing-helper API.", usage: {"status":"caution","licence":"Datamuse API terms; daily limits and acknowledgement requirements for public apps.","commercial":"Good for writing demos. Public apps should acknowledge Datamuse and respect limits.","notes":"Useful for autocomplete/writing helper."} },
  { id: "dictionary-api", name: "DictionaryAPI.dev English Definition", category: "Language", endpoint: "https://api.dictionaryapi.dev/api/v2/entries/en/engineering", responseType: "json", description: "Free English word definition API for language learning, search helper, and glossary demos.", usage: {"status":"caution","licence":"DictionaryAPI.dev free API; verify content/source rights for polished commercial redistribution.","commercial":"Good for learning and glossary demos. For production dictionary products, confirm content rights and service expectations.","notes":"The project states the API is always free; avoid abusive traffic and cache common words."} },
  { id: "artic", name: "Art Institute Chicago", category: "Media", endpoint: "https://api.artic.edu/api/v1/artworks?fields=id,title,artist_display,image_id,date_display&limit=8", responseType: "json", description: "Artwork records with images for gallery demos.", usage: {"status":"caution","licence":"Museum API/data rights; artwork image rights vary.","commercial":"Good for gallery demos. Verify image rights before commercial publication.","notes":"Show artist/source metadata."} },
  { id: "dog-ceo", name: "Dog CEO Images", category: "Media", endpoint: "https://dog.ceo/api/breeds/image/random/6", responseType: "json", description: "Random dog images for gallery and skeleton loading demos.", usage: {"status":"demo-only","licence":"Provider/API terms; image provenance may vary.","commercial":"Use as placeholder images only. Replace with licensed assets for business demos.","notes":"Placeholder media only."} },
  { id: "itunes-search", name: "iTunes Search API", category: "Media", endpoint: "https://itunes.apple.com/search?term=chatgpt&country=SG&media=software&limit=8", responseType: "json", description: "Apple iTunes/App Store search data.", usage: {"status":"caution","licence":"Apple iTunes Search API terms.","commercial":"Use for search/display demos under Apple terms. Do not repackage content.","notes":"Use official links and avoid implying endorsement."} },
  { id: "jikan-anime", name: "Jikan Anime Search", category: "Media", endpoint: "https://api.jikan.moe/v4/anime?q=naruto&limit=8", responseType: "json", description: "Anime catalogue search data.", usage: {"status":"demo-only","licence":"Jikan terms plus upstream MyAnimeList/content rights.","commercial":"Demo/learning only unless content rights are verified.","notes":"Do not use as commercial anime database without legal review."} },
  { id: "met-museum-object-detail", name: "Met Museum Object", category: "Media", endpoint: "https://collectionapi.metmuseum.org/public/collection/v1/objects/436535", responseType: "json", description: "Single Met Museum artwork record for gallery card demos.", usage: {"status":"business-ok","licence":"The Met Open Access data uses CC0 for selected datasets; API terms still apply.","commercial":"Good for commercial and noncommercial demos when record rights are clear.","notes":"No API key required. Check object-level rights and image availability."} },
  { id: "met-museum-search", name: "Met Museum Search", category: "Media", endpoint: "https://collectionapi.metmuseum.org/public/collection/v1/search?hasImages=true&q=singapore", responseType: "json", description: "Metropolitan Museum of Art collection search for gallery, culture and image-card demos.", usage: {"status":"business-ok","licence":"The Met Open Access data uses CC0 for selected datasets; API terms still apply.","commercial":"Good for commercial and noncommercial demos where records/images are available under Open Access.","notes":"No API key required. Limit request rate and check object-level image availability."} },
  { id: "musicbrainz", name: "MusicBrainz API", category: "Media", endpoint: "https://musicbrainz.org/ws/2/artist/?query=beatles&fmt=json&limit=8", responseType: "json", description: "Music metadata search for artist, album, and recording explorer demos.", usage: {"status":"noncommercial","licence":"MusicBrainz API terms; non-commercial web service is free; commercial plans required.","commercial":"Use no more than 1 request/sec and set meaningful user-agent when possible. Commercial usage needs plan/permission.","notes":"Cache and identify your app in production."} },
  { id: "tvmaze", name: "TVmaze Show Search", category: "Media", endpoint: "https://api.tvmaze.com/search/shows?q=office", responseType: "json", description: "TV show search with images, genres, status, and ratings.", usage: {"status":"caution","licence":"TVmaze API terms.","commercial":"Great for demos. Commercial/heavy catalogue usage needs terms/rate review.","notes":"Content/image rights may vary."} },
  { id: "citybikes", name: "CityBikes API", category: "Mobility", endpoint: "https://api.citybik.es/v2/networks", responseType: "json", description: "Bike sharing network and station data.", usage: {"status":"caution","licence":"CityBikes/PyBikes terms; source acknowledgement/link required.","commercial":"Good for mobility demos. For public apps, show source and avoid heavy polling.","notes":"Use attribution."} },
  { id: "osrm-route", name: "OSRM Route API", category: "Mobility", endpoint: "https://router.project-osrm.org/route/v1/driving/103.851959,1.290270;103.819839,1.352083?overview=false&steps=true", responseType: "json", description: "Open Source Routing Machine demo server route calculation.", usage: {"status":"caution","licence":"OSRM backend is open source; public demo server policy applies.","commercial":"Good for route demo. Do not use public demo server as production routing backend.","notes":"Self-host OSRM or use paid provider for production."} },
  { id: "open-food", name: "Open Food Facts Product", category: "Product", endpoint: "https://world.openfoodfacts.org/api/v2/product/737628064502.json", responseType: "json", description: "Barcode/product lookup for product finder and nutrition demos.", usage: {"status":"caution","licence":"Open Food Facts database/image licences; attribution/share-style obligations may apply.","commercial":"May be usable commercially if attribution/share rules are followed.","notes":"Check image/data rights."} },
  { id: "pubchem-compound", name: "PubChem Compound", category: "Science", endpoint: "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/caffeine/property/MolecularFormula,MolecularWeight,CanonicalSMILES/JSON", responseType: "json", description: "Chemistry compound lookup.", usage: {"status":"caution","licence":"PubChem/NCBI public data terms and source notices.","commercial":"Good for chemistry demos. Not safety/regulatory chemical advice.","notes":"Show source and CID."} },
  { id: "spacex", name: "SpaceX Launches", category: "Science", endpoint: "https://api.spacexdata.com/v5/launches/past", responseType: "json", description: "Historical SpaceX launch data.", usage: {"status":"demo-only","licence":"Unofficial/archived project terms.","commercial":"Use for demos only unless current project status and data rights are verified.","notes":"Not a dependable production source."} },
  { id: "spacedevs-events", name: "The Space Devs Events", category: "Science", endpoint: "https://ll.thespacedevs.com/2.3.0/events/?limit=8&ordering=-last_updated", responseType: "json", description: "Space events such as dockings, spacewalks, tests, and mission milestones.", requestHeaders: {"Accept": "application/json"}, usage: {"status":"caution","licence":"The Space Devs Launch Library 2 API terms; media/image licences vary by record.","commercial":"Good for demos. Free access is limited, and event media rights should be checked before commercial publication.","notes":"Free API data is available up to 15 requests per hour. Cache results and show source."} },
  { id: "spacedevs-launches", name: "The Space Devs Launches", category: "Science", endpoint: "https://ll.thespacedevs.com/2.3.0/launches/?limit=8&mode=list&ordering=-last_updated", responseType: "json", description: "Rocket launch records for space timeline, calendar, and science dashboard demos.", requestHeaders: {"Accept": "application/json"}, usage: {"status":"caution","licence":"The Space Devs Launch Library 2 API terms; media/image licences vary by record.","commercial":"Good for demos. Free access is limited, and media rights should be checked before commercial publication.","notes":"Free API data is available up to 15 requests per hour. Cache results and avoid image reuse unless licence is clear."} },
  { id: "data-gov-forecast-2hr", name: "data.gov.sg 2-Hour Forecast", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/2-hour-weather-forecast", responseType: "json", description: "Singapore 2-hour weather forecast areas for local weather, route, and operations dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source, cache where practical, and do not use as safety-critical weather advice."} },
  { id: "data-gov-24hr-forecast", name: "data.gov.sg 24-Hour Forecast", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/24-hour-weather-forecast", responseType: "json", description: "Singapore 24-hour weather forecast for local dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-4day-forecast", name: "data.gov.sg 4-Day Forecast", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/4-day-weather-forecast", responseType: "json", description: "Singapore 4-day weather forecast for planning, travel and operations dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-air-temperature", name: "data.gov.sg Air Temperature", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/air-temperature", responseType: "json", description: "Singapore air temperature readings by station for weather station and local dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-carpark", name: "data.gov.sg Carpark Availability", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/transport/carpark-availability", responseType: "json", description: "Singapore carpark availability records for mobility, mall, delivery, and location dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Good for demo dashboards; real navigation products should handle freshness and data gaps."} },
  { id: "data-gov-pm25", name: "data.gov.sg PM2.5", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/pm25", responseType: "json", description: "Singapore PM2.5 readings for air quality and environment dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-psi", name: "data.gov.sg PSI", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/psi", responseType: "json", description: "Singapore Pollutant Standards Index readings for haze and environment dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-rainfall", name: "data.gov.sg Rainfall", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/rainfall", responseType: "json", description: "Live Singapore rainfall readings by weather station for dashboard and alert-style demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Station readings can be sparse; handle missing stations and cache repeat requests."} },
  { id: "data-gov-relative-humidity", name: "data.gov.sg Relative Humidity", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/relative-humidity", responseType: "json", description: "Singapore relative humidity readings by station for weather dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-taxi", name: "data.gov.sg Taxi Availability", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/transport/taxi-availability", responseType: "json", description: "Singapore taxi availability GeoJSON.", usage: {"status":"caution","licence":"data.gov.sg / Singapore open data and dataset terms.","commercial":"Testing can be no-key. Production workflows should use an API key for limits/support.","notes":"Cache and follow data.gov.sg guidance."} },
  { id: "data-gov-traffic-images", name: "data.gov.sg Traffic Images", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/transport/traffic-images", responseType: "json", description: "Singapore traffic camera images for transport, routing, and live operations demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms; image/data usage rules apply.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Traffic images should be treated as live public-data demo content, not guaranteed CCTV service."} },
  { id: "data-gov-uv-index", name: "data.gov.sg UV Index", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/uv-index", responseType: "json", description: "Singapore UV index readings for weather, outdoor planning and health-style dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-wind-direction", name: "data.gov.sg Wind Direction", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/wind-direction", responseType: "json", description: "Singapore wind direction readings by station for weather and operations dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "data-gov-wind-speed", name: "data.gov.sg Wind Speed", category: "Singapore", endpoint: "https://api.data.gov.sg/v1/environment/wind-speed", responseType: "json", description: "Singapore wind speed readings by station for weather and operations dashboard demos.", usage: {"status":"caution","licence":"data.gov.sg public API / Singapore open data terms.","commercial":"No-key access is suitable for testing. Production workflows should use a data.gov.sg API key for higher limits and support.","notes":"Show source and cache repeated requests."} },
  { id: "bnm-exchange-rate", name: "BNM Exchange Rate", category: "Malaysia", endpoint: "https://api.bnm.gov.my/public/exchange-rate", responseType: "json", description: "Bank Negara Malaysia official MYR exchange rates against 27 major currencies from Interbank FX Market KL for fintech, ERP, and forex dashboard demos.", requestHeaders: {"Accept": "application/vnd.BNM.API.v1+json"}, usage: {"status":"business-ok","licence":"BNM Open API terms; data is for reference only and not for trading.","commercial":"Suitable for informational and dashboard use with source attribution. Not for live trading or financial products without BNM approval.","notes":"Returns 27 currencies with buying/selling/middle rates. Not financial advice."} },
  { id: "bnm-opr", name: "BNM Overnight Policy Rate", category: "Malaysia", endpoint: "https://api.bnm.gov.my/public/opr", responseType: "json", description: "Bank Negara Malaysia Overnight Policy Rate (OPR) — key monetary policy indicator for economics, finance, and banking demos.", requestHeaders: {"Accept": "application/vnd.BNM.API.v1+json"}, usage: {"status":"business-ok","licence":"BNM Open API terms; reference data only.","commercial":"Good for economics dashboards and banking demos with attribution. Not for trading decisions.","notes":"OPR changes are policy announcements; cache appropriately."} },
  { id: "bnm-base-rate", name: "BNM Base Rate", category: "Malaysia", endpoint: "https://api.bnm.gov.my/public/base-rate", responseType: "json", description: "Bank Negara Malaysia base lending rate and base financing rate across 35 financial institutions for banking and loan comparison demos.", requestHeaders: {"Accept": "application/vnd.BNM.API.v1+json"}, usage: {"status":"business-ok","licence":"BNM Open API terms.","commercial":"Good for loan calculator and banking dashboards with source shown.","notes":"Rates differ per institution; show institution name alongside rate."} },
  { id: "bnm-interest-rate", name: "BNM Interest Rate", category: "Malaysia", endpoint: "https://api.bnm.gov.my/public/interest-rate", responseType: "json", description: "Malaysia deposit and lending interest rate statistics from Bank Negara Malaysia for banking and savings dashboard demos.", requestHeaders: {"Accept": "application/vnd.BNM.API.v1+json"}, usage: {"status":"business-ok","licence":"BNM Open API terms.","commercial":"Good for savings and loan rate dashboards with attribution.","notes":"Not financial advice."} },
  { id: "bnm-kijang-emas", name: "BNM Kijang Emas Gold Price", category: "Malaysia", endpoint: "https://api.bnm.gov.my/public/kijang-emas", responseType: "json", description: "Bank Negara Malaysia official Kijang Emas gold coin buying and selling prices (1oz, 0.5oz, 0.25oz) for gold investment and commodity dashboard demos.", requestHeaders: {"Accept": "application/vnd.BNM.API.v1+json"}, usage: {"status":"business-ok","licence":"BNM Open API terms; reference price only.","commercial":"Good for commodity and investment dashboards with attribution. Not financial advice.","notes":"Updated daily. Show BNM as source."} },
  { id: "my-population", name: "Malaysia Population Statistics", category: "Malaysia", endpoint: "https://api.data.gov.my/data-catalogue/?id=population_malaysia&limit=20", responseType: "json", description: "Malaysia official population statistics by age, sex, and ethnicity from the Department of Statistics for demographics and research demos.", usage: {"status":"business-ok","licence":"Malaysia open data terms / data.gov.my.","commercial":"Good for demographic dashboards, HR analytics, and research tools with source attribution.","notes":"No API key required. Show DOSM as data source."} },
  { id: "my-gdp", name: "Malaysia GDP & GNI Annual", category: "Malaysia", endpoint: "https://api.data.gov.my/data-catalogue/?id=gdp_gni_annual_real&limit=20", responseType: "json", description: "Malaysia real GDP and GNI annual data (per capita included) from DOSM for economics, finance, and business dashboard demos.", usage: {"status":"business-ok","licence":"Malaysia open data terms / data.gov.my.","commercial":"Good for economics and business intelligence dashboards with source attribution.","notes":"No API key required. Show DOSM as data source."} },
  { id: "my-cpi", name: "Malaysia CPI Headline Inflation", category: "Malaysia", endpoint: "https://api.data.gov.my/data-catalogue/?id=cpi_headline&limit=20", responseType: "json", description: "Malaysia headline Consumer Price Index and inflation data from DOSM for economics and cost-of-living dashboard demos.", usage: {"status":"business-ok","licence":"Malaysia open data terms / data.gov.my.","commercial":"Good for economic indicator dashboards with source attribution.","notes":"No API key required. Show DOSM as data source."} },
  { id: "my-fuelprice", name: "Malaysia Weekly Fuel Price", category: "Malaysia", endpoint: "https://api.data.gov.my/data-catalogue/?id=fuelprice&limit=10", responseType: "json", description: "Malaysia weekly petrol and diesel pump prices (RON95, RON97, Diesel) from data.gov.my for fuel tracker, logistics cost, and ERP dashboard demos.", usage: {"status":"business-ok","licence":"Malaysia open data terms / data.gov.my.","commercial":"Good for logistics, fleet, and cost-of-living dashboards with source attribution.","notes":"No API key required. Show data.gov.my as data source."} },
  { id: "nhtsa-vpic", name: "NHTSA vPIC Vehicle API", category: "Vehicle", endpoint: "https://vpic.nhtsa.dot.gov/api/vehicles/getallmakes?format=json", responseType: "json", description: "Vehicle make/model/VIN reference data.", usage: {"status":"business-ok","licence":"NHTSA government/public data terms; no warranty.","commercial":"Generally suitable for demos and business tools with attribution/no-warranty awareness.","notes":"Good for vehicle admin demos."} },
  { id: "nws-weather", name: "NWS Weather API", category: "Weather", endpoint: "https://api.weather.gov/alerts/active?area=CA", responseType: "json", description: "US National Weather Service active alerts and forecast data.", usage: {"status":"business-ok","licence":"NWS open data terms; User-Agent and reasonable rate limits apply.","commercial":"Free for use under NWS open-data rules, but not a replacement for safety-critical alert systems.","notes":"Add app identity/User-Agent in production."} },
  { id: "air-quality", name: "Open-Meteo Air Quality", category: "Weather", endpoint: "https://air-quality-api.open-meteo.com/v1/air-quality?latitude=1.3521&longitude=103.8198&current=pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,ozone,us_aqi", responseType: "json", description: "Air quality metrics like PM2.5, PM10, ozone, and AQI.", usage: {"status":"noncommercial","licence":"Open-Meteo terms; free API is non-commercial only.","commercial":"Commercial dashboards/products should use paid terms.","notes":"Not medical or safety advice."} },
  { id: "open-meteo-geocode", name: "Open-Meteo Geocoding", category: "Weather", endpoint: "https://geocoding-api.open-meteo.com/v1/search?name=Singapore&count=8&language=en&format=json", responseType: "json", description: "City search returning coordinates, timezone, country, and admin areas.", usage: {"status":"noncommercial","licence":"Open-Meteo terms; attribution may apply.","commercial":"Commercial usage should follow paid/commercial terms.","notes":"Cache repeated location lookups."} },
  { id: "open-meteo-marine", name: "Open-Meteo Marine", category: "Weather", endpoint: "https://marine-api.open-meteo.com/v1/marine?latitude=1.2644&longitude=103.8222&current=wave_height,wave_direction,wave_period,sea_surface_temperature,ocean_current_velocity", responseType: "json", description: "Marine wave and sea condition data.", usage: {"status":"noncommercial","licence":"Open-Meteo terms; CC BY data terms may apply.","commercial":"Commercial port/logistics/travel apps should use paid terms.","notes":"Not a safety-critical marine navigation source."} },
  { id: "open-meteo", name: "Open-Meteo Weather", category: "Weather", endpoint: "https://api.open-meteo.com/v1/forecast?latitude=1.3521&longitude=103.8198&current=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m", responseType: "json", description: "Current weather data for dashboard, travel, route planning, and alert demos.", usage: {"status":"noncommercial","licence":"CC BY 4.0 data; free API is non-commercial only.","commercial":"Commercial apps should use an Open-Meteo paid/commercial plan.","notes":"Good for demo, education, and non-profit projects."} },
  { id: "sunrise-sunset", name: "Sunrise-Sunset", category: "Weather", endpoint: "https://api.sunrise-sunset.org/json?lat=1.3521&lng=103.8198&formatted=0&tzid=Asia/Singapore", responseType: "json", description: "Sunrise, sunset, twilight, solar noon, and day length by location.", usage: {"status":"caution","licence":"Provider terms; no API key required.","commercial":"Generally OK for lightweight demos. Verify terms for commercial redistribution.","notes":"Show source in polished demos."} },
] as const satisfies readonly PublicApiSpec[];

export function publicApiToolName(apiId: string): string {
  return `public_api_${apiId.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "").toLowerCase()}`;
}

function baseStructuredContent(spec: PublicApiSpec, status: string, httpStatus?: number, contentType?: string): Record<string, unknown> {
  return {
    apiId: spec.id,
    name: spec.name,
    category: spec.category,
    endpoint: spec.endpoint,
    usage: spec.usage,
    status,
    httpStatus,
    contentType
  };
}

async function readBoundedText(response: Response): Promise<string> {
  const contentLength = response.headers.get("content-length");
  if (contentLength && Number.parseInt(contentLength, 10) > maxBodyBytes) {
    throw new Error(`Response body exceeds ${maxBodyBytes} bytes.`);
  }
  const buffer = Buffer.from(await response.arrayBuffer());
  if (buffer.byteLength > maxBodyBytes) throw new Error(`Response body exceeds ${maxBodyBytes} bytes.`);
  return buffer.toString("utf8");
}

function parseJson(text: string): unknown {
  try {
    return JSON.parse(text);
  } catch (error) {
    throw new Error(error instanceof Error ? `Invalid JSON response: ${error.message}` : "Invalid JSON response.");
  }
}

function createTool(spec: PublicApiSpec): ToolModule {
  return {
    definition: {
      name: publicApiToolName(spec.id),
      description: `Call the no-key public API "${spec.name}" (${spec.category}) through a fixed allowlisted endpoint. Read-only live network call; usage status: ${spec.usage.status}.`,
      inputSchema: {
        type: "object",
        properties: {
          timeoutMs: { type: "number", minimum: 1000, maximum: 30000 },
          responseMode: { type: "string", enum: ["parsed", "raw"] }
        },
        additionalProperties: false
      }
    },
    enabledByDefault: true,
    schema: publicApiInputSchema,
    async handler(input) {
      const parsed = publicApiInputSchema.parse(input ?? {});
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), parsed.timeoutMs);
      try {
        const defaultAccept = spec.responseType === "json" ? "application/json, text/plain;q=0.9, */*;q=0.8" : "*/*";
        const mergedHeaders: Record<string, string> = { accept: defaultAccept };
        for (const [k, v] of Object.entries(spec.requestHeaders ?? {})) {
          if (k.toLowerCase() === "accept") mergedHeaders["accept"] = v;
          else mergedHeaders[k] = v;
        }
        const response = await safeFetch(spec.endpoint, { method: "GET", signal: controller.signal, headers: mergedHeaders });
        const contentType = response.headers.get("content-type") ?? "";
        const contentLength = response.headers.get("content-length");
        if (spec.responseType === "image" || contentType.toLowerCase().startsWith("image/")) {
          const structuredContent = { ...baseStructuredContent(spec, response.ok ? "success" : "http_error", response.status, contentType), metadata: { url: spec.endpoint, contentLength: contentLength ? Number.parseInt(contentLength, 10) : undefined } };
          return { ok: response.ok, summary: response.ok ? `Fetched image metadata for ${spec.name}.` : `${spec.name} returned HTTP ${response.status}.`, artifacts: [], structuredContent, logs: [JSON.stringify(structuredContent, null, 2)], errors: response.ok ? [] : [`HTTP ${response.status}`] };
        }
        const text = await readBoundedText(response);
        const structuredContent = response.ok
          ? parsed.responseMode === "raw" || spec.responseType !== "json"
            ? { ...baseStructuredContent(spec, "success", response.status, contentType), text: text.slice(0, textPreviewChars), truncated: text.length > textPreviewChars }
            : { ...baseStructuredContent(spec, "success", response.status, contentType), data: parseJson(text) }
          : { ...baseStructuredContent(spec, "http_error", response.status, contentType), text: text.slice(0, textPreviewChars), truncated: text.length > textPreviewChars };
        return {
          ok: response.ok,
          summary: response.ok ? `Fetched ${spec.name}.` : `${spec.name} returned HTTP ${response.status}.`,
          artifacts: [],
          structuredContent,
          logs: [JSON.stringify(structuredContent, null, 2)],
          errors: response.ok ? [] : [`HTTP ${response.status}`]
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Public API request failed.";
        return {
          ok: false,
          summary: `${spec.name} request failed: ${message}`,
          artifacts: [],
          structuredContent: { ...baseStructuredContent(spec, "error"), error: message },
          logs: [],
          errors: [message]
        };
      } finally {
        clearTimeout(timer);
      }
    }
  };
}

export const publicApiTools: ToolModule[] = publicApiRegistry.map(createTool);
