import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { callTool } from "../src/mcp/router.js";
import type { ToolContext } from "../src/mcp/types.js";
import { createProject, readProjectFile, writeProjectFile } from "../src/projects/store.js";
import { skillRegistry } from "../src/skills/registry.js";

function toolContext(root: string): ToolContext {
  return {
    publicBaseUrl: "https://example.test",
    workspaceRoot: root,
    commandTimeoutMs: 1000,
    shareRoot: path.join(root, "shares"),
    artifactRoot: path.join(root, "artifacts"),
    feedbackRoot: path.join(root, "feedback"),
    projectRoot: path.join(root, "projects"),
    clientId: "svg-optimization-test"
  };
}

test("optimize_project_svgs cleans SVGs, preserves labels, validates viewBox, and writes optimized outputs", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "svg-optimization-"));
  try {
    const ctx = toolContext(root);
    const project = await createProject(ctx.projectRoot, { title: "SVG project", createdByClientId: "coder" });
    await writeProjectFile(ctx.projectRoot, project.id, "icons/logo.svg", `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" inkscape:version="1.3" data-name="Layer 1">
  <!-- editor comment -->
  <title>Checkout icon</title>
  <desc>Cart checkout icon for navigation</desc>
  <metadata>Generated by editor</metadata>
  <g></g>
  <g><path d="M1 1h4v4H1z" fill="#111"/></g>
  <g><path d="M1 1h4v4H1z" fill="#111"/></g>
</svg>
`);
    await writeProjectFile(ctx.projectRoot, project.id, "icons/bad.svg", `<svg width="20" height="20"><rect width="20" height="20"/></svg>`);

    const result = await callTool("optimize_project_svgs", {
      projectId: project.id,
      applyOptimizations: true
    }, ctx);
    assert.equal(result.ok, true);
    assert.ok(result.artifacts.includes("svg-optimization/svg-optimization-report.json"));
    assert.ok(result.artifacts.includes("svg-optimization/svg-optimization-report.md"));
    assert.ok(result.artifacts.includes("optimized-svgs/icons/logo.optimized.svg"));

    const report = result.structuredContent as {
      totalReductionBytes: number;
      svgs: Array<{ path: string; optimizedPath?: string; applied: boolean; metrics: { hasValidViewBox: boolean; titlePreserved: boolean; descPreserved: boolean; removedMetadataBlocks: number; removedEditorAttributes: number; removedEmptyGroups: number; collapsedDuplicateGroups: number } }>;
      findings: Array<{ id: string; path: string }>;
    };
    assert.equal(report.svgs.length, 2);
    assert.equal(report.totalReductionBytes > 0, true);
    const logo = report.svgs.find((svg) => svg.path === "icons/logo.svg");
    assert.equal(logo?.applied, true);
    assert.equal(logo?.metrics.hasValidViewBox, true);
    assert.equal(logo?.metrics.titlePreserved, true);
    assert.equal(logo?.metrics.descPreserved, true);
    assert.equal(logo?.metrics.removedMetadataBlocks, 1);
    assert.equal(logo?.metrics.removedEditorAttributes >= 2, true);
    assert.equal(logo?.metrics.removedEmptyGroups, 1);
    assert.equal(logo?.metrics.collapsedDuplicateGroups, 1);
    assert.ok(report.findings.some((finding) => finding.id === "svg-cleanup-available" && finding.path === "icons/logo.svg"));
    assert.ok(report.findings.some((finding) => finding.id === "invalid-or-missing-viewbox" && finding.path === "icons/bad.svg"));
    assert.ok(report.findings.some((finding) => finding.id === "missing-accessibility-labels" && finding.path === "icons/bad.svg"));

    const optimized = await readProjectFile(ctx.projectRoot, project.id, "optimized-svgs/icons/logo.optimized.svg");
    assert.match(optimized, /<title>Checkout icon<\/title>/);
    assert.match(optimized, /<desc>Cart checkout icon for navigation<\/desc>/);
    assert.doesNotMatch(optimized, /metadata|inkscape|data-name|editor comment/);
    const markdown = await readProjectFile(ctx.projectRoot, project.id, "svg-optimization/svg-optimization-report.md");
    assert.match(markdown, /# SVG Optimization Report/);
    assert.match(markdown, /invalid-or-missing-viewbox/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("optimize_project_svgs supports scoped audit without applying changes", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "svg-optimization-"));
  try {
    const ctx = toolContext(root);
    const project = await createProject(ctx.projectRoot, { title: "Scoped SVGs", createdByClientId: "coder" });
    await writeProjectFile(ctx.projectRoot, project.id, "icons/a.svg", `<svg viewBox="0 0 10 10"><title>A</title><desc>A icon</desc><rect width="10" height="10"/></svg>`);
    await writeProjectFile(ctx.projectRoot, project.id, "icons/b.svg", `<svg><rect width="10" height="10"/></svg>`);

    const result = await callTool("optimize_project_svgs", {
      projectId: project.id,
      paths: ["icons/b.svg"],
      applyOptimizations: false
    }, ctx);
    assert.equal(result.ok, true);
    const report = result.structuredContent as { svgs: Array<{ path: string; applied: boolean }>; findings: Array<{ id: string; path: string }> };
    assert.deepEqual(report.svgs.map((svg) => svg.path), ["icons/b.svg"]);
    assert.equal(report.svgs[0]?.applied, false);
    assert.ok(report.findings.some((finding) => finding.id === "invalid-or-missing-viewbox" && finding.path === "icons/b.svg"));
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("SVG optimization is exposed through coding and debug skills", () => {
  for (const skillId of ["coding", "debug"]) {
    const skill = skillRegistry.find((entry) => entry.id === skillId);
    assert.ok(skill, `${skillId} skill exists`);
    assert.ok(skill!.toolNames.includes("optimize_project_svgs"), `${skillId} exposes optimize_project_svgs`);
  }
});
